# Generated by Django 5.0.6 on 2024-05-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('coach', 'Coach'), ('athlete', 'Athlete')], default='athlete', max_length=50),
        ),
    ]
